url: "https://le0nag.github.io"
github_username: le0nag

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# remote_theme: b2a3e8/jekyll-theme-console

# Math rendering
markdown: kramdown
kramdown:
  math_engine: mathjax

# MathJax configuration
# mathjax:
#   source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
#   config: 'MathJax.Hub.Config({tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]], displayMath: [["$$","$$"],["\\[","\\]"]], processEscapes: true}});'

title: The White Rabbit Hole

header_pages:
  - index.md
  - about.md

style: dark


disable_google_fonts: false